/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.adminImplements;
import controllers.adminInterface;
import controllers.facCrudImplements;
import controllers.facCrudInterface;
import controllers.quizImplements;
import controllers.quizInterface;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import models.Faculty;
import models.Quiz;
import models.Student;
import static views.stdntAvailableQuizzes.stdId;

/**
 *
 * @author ALI
 */
public class adminFacVerifPanel extends javax.swing.JFrame {

    /**
     * Creates new form facVerifPanel
     */
    private static List<Faculty> availFacList;
    public static int facId;
    public adminFacVerifPanel() {
        initComponents();
        availFacList = new ArrayList<>();
        displayFacultyList();
    }
    private void displayFacultyList(){
        facCrudInterface interfc = new facCrudImplements();
        availFacList = interfc.getAllFaculty();
        DefaultTableModel dft = (DefaultTableModel)facRecTable.getModel();
        for(Faculty fac:availFacList){
                dft.addRow(new Object[]{fac.getFacId(), fac.getFacName(), fac.getFacEmail(), fac.getFacPhone(), fac.getFacGender(), fac.getFacStatus(), fac.getFacApprovalStatus()});
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        facRecTable = new javax.swing.JTable();
        delBtn = new javax.swing.JButton();
        approveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        facRecTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FacId", "FacName", "FacEmail", "FacPhone", "FacGender", "FacType", "FacApprovalStatus"
            }
        ));
        jScrollPane1.setViewportView(facRecTable);
        if (facRecTable.getColumnModel().getColumnCount() > 0) {
            facRecTable.getColumnModel().getColumn(6).setMinWidth(150);
            facRecTable.getColumnModel().getColumn(6).setMaxWidth(300);
        }

        delBtn.setText("Delete Faculty");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        approveBtn.setText("Approve Faculty");
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(delBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(approveBtn)
                .addGap(195, 195, 195))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delBtn)
                    .addComponent(approveBtn))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        int rowIndex = facRecTable.getSelectedRow();
        if(rowIndex < 0){
            JOptionPane.showMessageDialog(null, "Please select any record!");
        }
        else{
        TableModel tblModel = facRecTable.getModel();
        int selectedFacId = (int)facRecTable.getValueAt(rowIndex,0);  
        Faculty fac = new Faculty();
        fac.setFacId(selectedFacId);
        adminInterface interfc = new adminImplements();
        interfc.approveFaculty(fac);        
        }
    }//GEN-LAST:event_approveBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        int rowIndex = facRecTable.getSelectedRow();
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this faculty?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (option==JOptionPane.YES_OPTION) {
            if(rowIndex < 0){
            JOptionPane.showMessageDialog(null, "Please select any record!");
        }
            else{
                TableModel tblModel = facRecTable.getModel();
        int selectedFacId = (int)facRecTable.getValueAt(rowIndex,0);  
        Faculty fac = new Faculty();
        fac.setFacId(selectedFacId);
        adminInterface interfc = new adminImplements();
        interfc.deleteFaculty(fac);
        adminFacVerifPanel obj = new adminFacVerifPanel();
        obj.setVisible(true);
        this.setVisible(false);
            }        
        }
        else if (option==JOptionPane.NO_OPTION) {
        adminFacVerifPanel obj = new adminFacVerifPanel();
        obj.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_delBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminFacVerifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminFacVerifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminFacVerifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminFacVerifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminFacVerifPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JTable facRecTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
