/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.adminImplements;
import controllers.adminInterface;
import controllers.facCrudImplements;
import controllers.facCrudInterface;
import controllers.stdCrudImplements;
import controllers.stdCrudInterface;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import models.Faculty;
import models.Student;

/**
 *
 * @author ALI
 */
public class adminStdVerifPanel extends javax.swing.JFrame {

    /**
     * Creates new form adminStdVerifPanel
     */
    private static List<Student> availStdList;
    public adminStdVerifPanel() {
        initComponents();
        availStdList = new ArrayList<>();
        displayFacultyList();
    }
    private void displayFacultyList(){
        stdCrudInterface interfc = new stdCrudImplements();
        availStdList = interfc.getAllStudents();
        DefaultTableModel dft = (DefaultTableModel)stdntRecTbl.getModel();
        for(Student std:availStdList){
                dft.addRow(new Object[]{std.getStdId(), std.getStdName(), std.getStdEmail(), std.getStdPhone(), std.getStdGender(), std.getStdApprovStatus()});
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stdntRecTbl = new javax.swing.JTable();
        stdApproveBtn = new javax.swing.JButton();
        delStdBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        stdntRecTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StdntId", "StdntName", "StdntEmail", "StdntPhone", "StdntGender", "StdntApprovalStatus"
            }
        ));
        jScrollPane1.setViewportView(stdntRecTbl);
        if (stdntRecTbl.getColumnModel().getColumnCount() > 0) {
            stdntRecTbl.getColumnModel().getColumn(5).setMinWidth(150);
            stdntRecTbl.getColumnModel().getColumn(5).setMaxWidth(300);
        }

        stdApproveBtn.setText("Approve Student");
        stdApproveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdApproveBtnActionPerformed(evt);
            }
        });

        delStdBtn.setText("Delete Student");
        delStdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delStdBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(delStdBtn)
                .addGap(160, 160, 160)
                .addComponent(stdApproveBtn)
                .addGap(212, 212, 212))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdApproveBtn)
                    .addComponent(delStdBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stdApproveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdApproveBtnActionPerformed
        int rowIndex = stdntRecTbl.getSelectedRow();
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to approve this student?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (option==JOptionPane.YES_OPTION) {
            TableModel tblModel = stdntRecTbl.getModel();
        int selectedStdId = (int)stdntRecTbl.getValueAt(rowIndex,0);  
        Student std = new Student();
        std.setStdId(selectedStdId);
        adminInterface interfc = new adminImplements();
        interfc.approveStudent(std);
        admnPanel obj = new admnPanel();
        obj.setVisible(true);
        this.setVisible(false);
        }
        if(rowIndex < 0){
            JOptionPane.showMessageDialog(null, "Please select any record!");
        }
    }//GEN-LAST:event_stdApproveBtnActionPerformed

    private void delStdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delStdBtnActionPerformed
        int rowIndex = stdntRecTbl.getSelectedRow();
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this student?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (option==JOptionPane.YES_OPTION) {
            if(rowIndex < 0){
            JOptionPane.showMessageDialog(null, "Please select any record!");
        }
            else{
                TableModel tblModel = stdntRecTbl.getModel();
        int selectedStdId = (int)stdntRecTbl.getValueAt(rowIndex,0);  
        Student std = new Student();
        std.setStdId(selectedStdId);
        adminInterface interfc = new adminImplements();
        interfc.deleteStudent(std);
        adminFacVerifPanel obj = new adminFacVerifPanel();
        obj.setVisible(true);
        this.setVisible(false);
            }        
        }
        else if (option==JOptionPane.NO_OPTION) {
        adminFacVerifPanel obj = new adminFacVerifPanel();
        obj.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_delStdBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminStdVerifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminStdVerifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminStdVerifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminStdVerifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminStdVerifPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delStdBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton stdApproveBtn;
    private javax.swing.JTable stdntRecTbl;
    // End of variables declaration//GEN-END:variables
}
