/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.adminImplements;
import controllers.adminInterface;
import controllers.facCrudImplements;
import controllers.facCrudInterface;
import controllers.stdCrudImplements;
import controllers.stdCrudInterface;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import models.Faculty;
import models.Student;

/**
 *
 * @author ALI
 */
public class adminStdVerifPanel extends javax.swing.JFrame {

    /**
     * Creates new form adminStdVerifPanel
     */
    private static List<Student> availStdList;
    public adminStdVerifPanel() {
        initComponents();
        availStdList = new ArrayList<>();
        displayStdList();
    }
    private void displayStdList(){
        stdCrudInterface interfc = new stdCrudImplements();
        availStdList = interfc.getAllStudents();
        DefaultTableModel dft = (DefaultTableModel)stdntRecTbl.getModel();
        for(Student std:availStdList){
                dft.addRow(new Object[]{std.getStdId(), std.getStdName(), std.getStdEmail(), std.getStdPhone(), std.getStdGender(), std.getStdApprovStatus()});
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stdntRecTbl = new javax.swing.JTable();
        stdApproveBtn = new javax.swing.JButton();
        delStdBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBackToFacPanel = new javax.swing.JLabel();
        facQuizAdditionPnlCloseBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 118, 211));

        stdntRecTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StdntId", "StdntName", "StdntEmail", "StdntPhone", "StdntGender", "StdntApprovalStatus"
            }
        ));
        jScrollPane1.setViewportView(stdntRecTbl);
        if (stdntRecTbl.getColumnModel().getColumnCount() > 0) {
            stdntRecTbl.getColumnModel().getColumn(5).setMinWidth(150);
            stdntRecTbl.getColumnModel().getColumn(5).setMaxWidth(300);
        }

        stdApproveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stdApproveBtn.setText("Approve Student");
        stdApproveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdApproveBtnActionPerformed(evt);
            }
        });

        delStdBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        delStdBtn.setText("Delete Student");
        delStdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delStdBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Student Verification Panel");

        btnBackToFacPanel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnBackToFacPanel.setForeground(new java.awt.Color(242, 242, 242));
        btnBackToFacPanel.setText("<-");
        btnBackToFacPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackToFacPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackToFacPanelMouseClicked(evt);
            }
        });

        facQuizAdditionPnlCloseBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        facQuizAdditionPnlCloseBtn.setForeground(new java.awt.Color(255, 255, 255));
        facQuizAdditionPnlCloseBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        facQuizAdditionPnlCloseBtn.setText("X");
        facQuizAdditionPnlCloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        facQuizAdditionPnlCloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facQuizAdditionPnlCloseBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(btnBackToFacPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(facQuizAdditionPnlCloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(delStdBtn)
                .addGap(32, 32, 32)
                .addComponent(stdApproveBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facQuizAdditionPnlCloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackToFacPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdApproveBtn)
                    .addComponent(delStdBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stdApproveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdApproveBtnActionPerformed
        int rowIndex = stdntRecTbl.getSelectedRow();
        if(rowIndex < 0){
            JOptionPane.showMessageDialog(null, "Please select any record to proceed!");
        }
        else{
            int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to approve this student?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (option==JOptionPane.YES_OPTION) {
                TableModel tblModel = stdntRecTbl.getModel();
            int selectedStdId = (int)stdntRecTbl.getValueAt(rowIndex,0);  
            Student std = new Student();
            std.setStdId(selectedStdId);
            adminInterface interfc = new adminImplements();
            interfc.approveStudent(std);
            DefaultTableModel dft = (DefaultTableModel)stdntRecTbl.getModel();
            dft.setRowCount(0);
            displayStdList();
//        admnPanel obj = new admnPanel();
//        obj.setVisible(true);
//        this.setVisible(false);
        }
        
        }
        
    }//GEN-LAST:event_stdApproveBtnActionPerformed

    private void delStdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delStdBtnActionPerformed
        int rowIndex = stdntRecTbl.getSelectedRow();
        if(rowIndex < 0){
            JOptionPane.showMessageDialog(null, "Please select any record!");
        }
        else{
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this student?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (option==JOptionPane.YES_OPTION) {
                TableModel tblModel = stdntRecTbl.getModel();
                int selectedStdId = (int)stdntRecTbl.getValueAt(rowIndex,0);  
                Student std = new Student();
                std.setStdId(selectedStdId);
                adminInterface interfc = new adminImplements();
                interfc.deleteStudent(std);
                DefaultTableModel dft = (DefaultTableModel)stdntRecTbl.getModel();
                dft.setRowCount(0);
                displayStdList();
//              adminFacVerifPanel obj = new adminFacVerifPanel();
//              obj.setVisible(true);
//              this.setVisible(false);

  
        }
        else if (option==JOptionPane.NO_OPTION) {
        adminFacVerifPanel obj = new adminFacVerifPanel();
        obj.setVisible(true);
        this.setVisible(false);
        }
            }      
        
    }//GEN-LAST:event_delStdBtnActionPerformed

    private void btnBackToFacPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackToFacPanelMouseClicked
        FacultyPanel facPnl = new FacultyPanel();
        this.dispose();
        facPnl.setVisible(true);
    }//GEN-LAST:event_btnBackToFacPanelMouseClicked

    private void facQuizAdditionPnlCloseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facQuizAdditionPnlCloseBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_facQuizAdditionPnlCloseBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminStdVerifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminStdVerifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminStdVerifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminStdVerifPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminStdVerifPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBackToFacPanel;
    private javax.swing.JButton delStdBtn;
    private javax.swing.JLabel facQuizAdditionPnlCloseBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton stdApproveBtn;
    private javax.swing.JTable stdntRecTbl;
    // End of variables declaration//GEN-END:variables
}
